#!/bin/bash
### BEGIN INIT INFO
# Provides:          nidan.py
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Nidan Agent startup script
# Description:       Nidan Agent startup script
### END INIT INFO

STARTCOMMAND=nidan.py

case "$1" in
start)  echo "Launch Nidan agent:"
	$STARTCOMMAND &
        ;;
stop)   pid=`pgrep nidan.py`
	echo "Killing Nidan agent (PID: $pid)"
	kill -HUP $pid
        ;;
restart) echo "Not yet implemented"
        ;;
reload|force-reload) echo "Not yet implemented"
        ;;
*)      echo "Usage: /etc/init.d/nidan {start|stop|restart|reload|force-reload}"
        exit 2
        ;;
esac
exit 0